language: go
go:
 - "1.12"
 - "1.13"
 - "tip"

addons:
  postgresql: "9.6"

services:
  - postgresql

install:
  - go install github.com/hexya-erp/hexya
  - npm install less -g

before_script:
  - hexya generate -t .

script:
  - travis_wait go test -v ./...

env:
  - HEXYA_DB_DRIVER=postgres HEXYA_DB_USER=postgres HEXYA_DB_PASSWORD= HEXYA_DB_PREFIX=hexya_test GO111MODULE=on GOMAXPROCS=2 GOGC=20
